name: flutter_lab
description: In this project i try to learn new libraries and build mini-projects with them.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  permission_handler: ^10.1.0
  flutter_hooks: ^0.18.5+1
  get: ^4.6.5

  #firebase sdk's
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_core: ^1.4.0
  cloud_functions: ^3.0.0
  firebase_storage: ^10.0.1
  hooks_riverpod: ^2.0.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
